### ISSUE TITLE
SQL Server to SIARD error "conversion from Clob to AsciiStream is unsupported" due to collation 

### ISSUE THREAD

**Issue by pi-r-ayotte** [sfa-siard/siard-suite#99] opened 2024-05-17 14:29 UTC
OS: Windows 2022
SQL Server: 2022
Database: Restored from a SQL Server 2012 backup
Siard-Suite: 2.2.147 (Windows)

When i try to export SQL Server Databse with "" Collation i end up with error "com.microsoft.sqlserver.jdbc.SQLServerException: The conversion from Clob to AsciiStream is unsupported".

To reproduce the problem:

1. Create an empty database TestClob with the collation ""
2. Run the script in attachement to create a test table with one row
3. Try to export using and siard-from-db.bat you should have the error
4. Drop the table
5. Change the collation to ""
6. Rerun the script to create the test table
7. The export should now terminate succesfully using siard-from-db.bat

Now i cannot change the collation because there are function in the database which are collation dependant and also because there could be data con

**Comment by Amasit** [comment] 2024-08-08 11:39
Duplicate of #100

**Closed** 2024-08-08 11:40 UTC
Labels: bug
