### ISSUE TITLE
Unable to connect to Oracle database (19.21.0.0.0)

### ISSUE THREAD

**Issue by MarkusGehrig** [sfa-siard/siard-suite#93] opened 2024-04-12 09:59 UTC
When we try to connect to our database running Oracle Database 19c Enterprise Edition, we can enter the connection details without any problem or error message. However, on the next 'Preview' page it loads and loads with no progress. On the database we see that there is no open session and no failed login attempt for the user being used.

We have also entered an incorrect password and no error is displayed either.

Is there a log file or something we can add to this report to help you, just ask.

Database: Oracle Database 19c Enterprise Edition Release 19.21.0.0.0
SIARD Version: 2.2.141 (exe-installer with jre)

**Comment by mburri** [comment] 2024-04-12 11:07
@MarkusGehrig 
I think this is a duplicate of: https://github.com/sfa-siard/JdbcOracle/issues/4

That should be fixed with SIARD-Suite-2.2.145
This version is not yet officially released but you can download it from here: https://github.com/sfa-siard/siard-suite/actions/runs/8659551058#artifacts 

It would be really helpful if you could confirm that your issue is resolved with SIARD-Suite-2.2.145

Regarding your question about the log files: We have changed the logging strategy since 2.2.141. You should find the siard logs at  `${user.home}/SIARD-Suite/`

I hope this helps. Please let me know if you have more questions.

**Comment by MarkusGehrig** [comment] 2024-04-12 13:23
**@mburri**

Thanks for your help. 
At the moment it looks like it is fixed. 

Do you have any idea when this fix will be officially released?

**Comment by mburri** [comment] 2024-04-12 13:58
No, I don't know. But I think it's perfectly fine for now to use SIARD Suite 2.2.145 if it works for you.
It is a release candidate that is ready to be released. If we add new features or fix some more bugs, we will create a new version. SIARD Suite 2.2.145 will not change. 
I recommend to follow the repository - then you will be notified if a new release is ready.

I'm closing the issue, since this is a duplicate of https://github.com/sfa-siard/JdbcOracle/issues/4 and it seems to be fixed for you.

**Closed by mburri** 2024-04-12 13:58 UTC

**Comment by MarkusGehrig** [comment] 2024-04-12 14:27
So I tried to export one of our databases. At first it looks like it is going through. But it looks like it got stuck.

![image](https://github.com/sfa-siard/siard-suite/assets/15866860/df2c6fb6-688b-42a9-bf2e-225968064381)

The last line in the log is
2024-04-12 15:51:52,067 DEBUG [Thread-4] c.a.bar.siard2.cmd.MetaDataFromDb - Size of table 'SLO7.TEST' successfully determined

I let it run for now, maybe the database is a bit big. (Approximately 2000 tables and 2.5TB of data)
